apiVersion: v2
name: gogallery
version: 0.0.1
description: A simple photo gallery written in Go
type: application
home: https://github.com/hsmade/gogallery
maintainers:
  - name: Wim Fournier
    email: gogallery@fournier.nl
