frontend:
  image: hsmade/gogallery-frontend:latest
  replicas: 1
backend:
  image: hsmade/gogallery-backend:latest
  replicas: 1
  rootPath: /foo/bar
  verbose: true
ingress:
  hostname: www.domain.tld
  istio:
    enabled: false # don't register an `Ingress` but register a `VirtualService` instead
    gateway: public # the istio gateway to bind to
