apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: gogallery
build:
  artifacts:
  - image: backend
    docker:
      dockerfile: Dockerfile.backend
  - image: frontend
    docker:
      dockerfile: Dockerfile.frontend
deploy:
  helm:
    releases:
      - name: gogallery
        chartPath: chart
        setValues:
          ingress.istio.enabled: false
          backend.rootPath: /app/pkg/testfiles
        artifactOverrides:
          frontend.image: frontend
          backend.image: backend
