apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          args:
            - "-root-path"
            {{- if .Values.backend.rootPathFromHost }}
            - "/data"
            {{- else }}
            - {{ .Values.backend.rootPath }}
            {{- end }}
            {{- if .Values.backend.verbose }}
            - "-verbose"
            {{- end }}
          resources:
            limits:
              cpu: "{{ .Values.backend.cpuLimit }}"
          ports:
            - containerPort: 80
              name: http
{{- if .Values.backend.rootPathFromHost }}
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.backend.rootPath }}
            type: Directory
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80
              name: http