{{ if not .Values.ingress.istio.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
    - http:
        paths:
          - path: /list
            pathType: Prefix
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: 80
          - path: /download
            pathType: Prefix
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: 80
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ .Release.Name }}-frontend
              servicePort: 80
{{ end }}
