apiVersion: v1
kind: Service
metadata:
  name: gogallery-backend
spec:
  selector:
    app: gogallery-backend
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gogallery-frontend
spec:
  selector:
    app: gogallery-frontend
  ports:
    - port: 80
