// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: thumbs.protobuf

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Thumbs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumb []*Thumb `protobuf:"bytes,1,rep,name=thumb,proto3" json:"thumb,omitempty"`
}

func (x *Thumbs) Reset() {
	*x = Thumbs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thumbs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thumbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thumbs) ProtoMessage() {}

func (x *Thumbs) ProtoReflect() protoreflect.Message {
	mi := &file_thumbs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thumbs.ProtoReflect.Descriptor instead.
func (*Thumbs) Descriptor() ([]byte, []int) {
	return file_thumbs_proto_rawDescGZIP(), []int{0}
}

func (x *Thumbs) GetThumb() []*Thumb {
	if x != nil {
		return x.Thumb
	}
	return nil
}

type Thumb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exifdata  []byte `protobuf:"bytes,2,opt,name=exifdata,proto3" json:"exifdata,omitempty"`
	Thumbnail []byte `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
}

func (x *Thumb) Reset() {
	*x = Thumb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thumbs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Thumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thumb) ProtoMessage() {}

func (x *Thumb) ProtoReflect() protoreflect.Message {
	mi := &file_thumbs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thumb.ProtoReflect.Descriptor instead.
func (*Thumb) Descriptor() ([]byte, []int) {
	return file_thumbs_proto_rawDescGZIP(), []int{1}
}

func (x *Thumb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Thumb) GetExifdata() []byte {
	if x != nil {
		return x.Exifdata
	}
	return nil
}

func (x *Thumb) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

var File_thumbs_proto protoreflect.FileDescriptor

var file_thumbs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x06, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x73, 0x12,
	0x22, 0x0a, 0x05, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x52, 0x05, 0x74, 0x68,
	0x75, 0x6d, 0x62, 0x22, 0x55, 0x0a, 0x05, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x69, 0x66, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x69, 0x66, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x73, 0x6d, 0x61, 0x64, 0x65, 0x2f,
	0x67, 0x6f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x68,
	0x75, 0x6d, 0x62, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_thumbs_proto_rawDescOnce sync.Once
	file_thumbs_proto_rawDescData = file_thumbs_proto_rawDesc
)

func file_thumbs_proto_rawDescGZIP() []byte {
	file_thumbs_proto_rawDescOnce.Do(func() {
		file_thumbs_proto_rawDescData = protoimpl.X.CompressGZIP(file_thumbs_proto_rawDescData)
	})
	return file_thumbs_proto_rawDescData
}

var file_thumbs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thumbs_proto_goTypes = []interface{}{
	(*Thumbs)(nil), // 0: protobuf.Thumbs
	(*Thumb)(nil),  // 1: protobuf.Thumb
}
var file_thumbs_proto_depIdxs = []int32{
	1, // 0: protobuf.Thumbs.thumb:type_name -> protobuf.Thumb
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_thumbs_proto_init() }
func file_thumbs_proto_init() {
	if File_thumbs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thumbs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thumbs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thumbs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Thumb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thumbs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thumbs_proto_goTypes,
		DependencyIndexes: file_thumbs_proto_depIdxs,
		MessageInfos:      file_thumbs_proto_msgTypes,
	}.Build()
	File_thumbs_proto = out.File
	file_thumbs_proto_rawDesc = nil
	file_thumbs_proto_goTypes = nil
	file_thumbs_proto_depIdxs = nil
}
